general:
  num_files_initial: 16
  num_files_final: 20
  time_cycle: 5
  status:
    - excellent
    - good
    - warning
    - faulty
    - killed
    - unknown
  missions:
    - ORBONE
    - CLNM
    - TMRS
    - GALXONE
    - UNKN
  devices:
    - Satellite
    - Space_Suit
    - Space_vehicle
    - Space_rockets
    - Space_tools
  date_format: "%d%m%Y%H%M%S"
